require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('../models/User');
const Client = require('../models/Client');
const Case = require('../models/Case');
const Document = require('../models/Document');
const Invoice = require('../models/Invoice');
const Task = require('../models/Task');
const CalendarEvent = require('../models/CalendarEvent');

const COURTS = { SC:'Supreme Court of India', BHC:'Bombay High Court', DHC:'Delhi High Court', DCMUM:'District Court, Mumbai', DCDEL:'District Court, Delhi', DCHYD:'District Court, Hyderabad' };

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB.');

    // Clear all collections
    await Promise.all([
      User.deleteMany({}),
      Client.deleteMany({}),
      Case.deleteMany({}),
      Document.deleteMany({}),
      Invoice.deleteMany({}),
      Task.deleteMany({}),
      CalendarEvent.deleteMany({})
    ]);
    console.log('Cleared all collections.');

    // === USERS ===
    const users = await User.create([
      { name: 'Rajesh Kumar', email: 'admin@legalflow.in', password: 'admin123', role: 'admin', phone: '+91 98765 00001', designation: 'Senior Partner' },
      { name: 'Priya Nair', email: 'priya@legalflow.in', password: 'lawyer123', role: 'lawyer', phone: '+91 98765 00002', designation: 'Associate' },
      { name: 'Suresh Iyer', email: 'suresh@legalflow.in', password: 'lawyer123', role: 'lawyer', phone: '+91 98765 00003', designation: 'Senior Associate' },
      { name: 'Meera Desai', email: 'meera@legalflow.in', password: 'lawyer123', role: 'lawyer', phone: '+91 98765 00004', designation: 'Associate' },
      { name: 'Amit Sharma', email: 'amit@legalflow.in', password: 'lawyer123', role: 'lawyer', phone: '+91 98765 00005', designation: 'Junior Associate' },
      { name: 'Kavita Reddy', email: 'kavita@legalflow.in', password: 'lawyer123', role: 'lawyer', phone: '+91 98765 00006', designation: 'Associate' }
    ]);
    console.log(`Created ${users.length} users.`);

    const userMap = {};
    users.forEach(u => { userMap[u.name] = u._id; });

    // === CLIENTS ===
    const clientsData = [
      { name:'Reliance Industries Ltd.', contact:'Mukesh Ambani', email:'legal@reliance.com', phone:'+91 22 3555 5000', address:'Maker Chambers IV, Nariman Point, Mumbai 400021', type:'Corporate', industry:'Conglomerate', gst:'27AAACR5055K1ZR', pan:'AAACR5055K', status:'Active', createdBy: userMap['Rajesh Kumar'] },
      { name:'Infosys Limited', contact:'Salil Parekh', email:'legal@infosys.com', phone:'+91 80 2852 0261', address:'Electronics City, Hosur Road, Bangalore 560100', type:'Corporate', industry:'IT Services', gst:'29AABCI1234K1Z5', pan:'AABCI1234K', status:'Active', createdBy: userMap['Rajesh Kumar'] },
      { name:'Tata Consultancy Services', contact:'K Krithivasan', email:'legal@tcs.com', phone:'+91 22 6778 9999', address:'TCS House, Raveline Street, Mumbai 400001', type:'Corporate', industry:'IT Services', gst:'27AABCT1234K1ZS', pan:'AABCT1234K', status:'Active', createdBy: userMap['Rajesh Kumar'] },
      { name:'Adani Group', contact:'Gautam Adani', email:'legal@adani.com', phone:'+91 79 2555 7500', address:'Adani House, Nr. Mithakhali, Ahmedabad 380009', type:'Corporate', industry:'Infrastructure', gst:'24AABCA1234K1ZM', pan:'AABCA1234K', status:'Active', createdBy: userMap['Rajesh Kumar'] },
      { name:'Arun Mehta', contact:'Arun Mehta', email:'arun.mehta@gmail.com', phone:'+91 98765 43210', address:'45-B, Bandra West, Mumbai 400050', type:'Individual', industry:'Personal', pan:'ABCPM1234L', status:'Active', createdBy: userMap['Rajesh Kumar'] },
      { name:'Priya Sharma', contact:'Priya Sharma', email:'priya.sharma@outlook.com', phone:'+91 99887 66554', address:'12, Vasant Vihar, New Delhi 110057', type:'Individual', industry:'Personal', pan:'ABCPS5678M', status:'Active', createdBy: userMap['Rajesh Kumar'] },
      { name:'Wipro Limited', contact:'Thierry Delaporte', email:'legal@wipro.com', phone:'+91 80 2844 0011', address:'Doddakannelli, Sarjapur Road, Bangalore 560035', type:'Corporate', industry:'IT Services', gst:'29AABCW1234K1Z3', pan:'AABCW1234K', status:'Active', createdBy: userMap['Rajesh Kumar'] },
      { name:'Bajaj Auto Ltd.', contact:'Rajiv Bajaj', email:'legal@bajajauto.com', phone:'+91 20 6610 6000', address:'Akurdi, Pune 411035', type:'Corporate', industry:'Automotive', gst:'27AABCB1234K1Z8', pan:'AABCB1234K', status:'Active', createdBy: userMap['Rajesh Kumar'] }
    ];
    const clients = await Client.create(clientsData);
    console.log(`Created ${clients.length} clients.`);

    const clientMap = {};
    clients.forEach(c => { clientMap[c.name] = c._id; });

    // === CASES ===
    const casesData = [
      { caseNumber:'WP(C) 1234/2025', diaryNumber:'D-45678/2025', title:'Reliance Industries vs. Union of India', client:clientMap['Reliance Industries Ltd.'], clientName:'Reliance Industries Ltd.', courtKey:'SC', courtName:COURTS.SC, bench:'Division Bench – Justice D.Y. Chandrachud, Justice J.B. Pardiwala', opposingParty:'Union of India', advocate:userMap['Rajesh Kumar'], advocateName:'Adv. Rajesh Kumar', filingType:'Writ Petition (Civil)', status:'Active', priority:'Critical', stage:4, filingDate:'2024-08-15', registrationDate:'2024-08-20', nextHearingDate:'2026-04-04', lastOrderDate:'2026-03-18', filingDeadline:'2026-04-10', lastHearingOutcome:'Evidence recording partially completed. Next date for cross-examination.', causeListRef:'Cause List No. 52, Item 8, Court No. 3', nextActionDate:'2026-04-03', description:'Constitutional challenge regarding regulatory framework applicability to telecom sector.', billingType:'Milestone-Based', totalBilled:4500000, totalPaid:3000000, adjournmentHistory:[{date:'2025-12-15',reason:'Bench not available due to Constitution Bench hearing',nextDate:'2026-01-20'},{date:'2026-01-20',reason:'Advocate for respondent sought adjournment for preparation',nextDate:'2026-02-15'},{date:'2026-02-15',reason:'Court proceedings adjourned due to judges conference',nextDate:'2026-03-18'}], timeline:[{date:'2024-08-15',type:'Filing',description:'Writ Petition filed before Supreme Court'},{date:'2024-08-20',type:'Registration',description:'Case registered and diary number assigned'},{date:'2024-09-10',type:'Hearing',description:'Admission hearing – case admitted for hearing'},{date:'2024-11-05',type:'Order',description:'Written statement directed to be filed within 30 days'},{date:'2025-01-15',type:'Filing',description:'Written statement filed by respondent'},{date:'2025-04-20',type:'Stage',description:'Matter moved to Evidence stage'},{date:'2025-12-15',type:'Adjournment',description:'Bench not available'},{date:'2026-01-20',type:'Adjournment',description:'Respondent sought adjournment'},{date:'2026-03-18',type:'Hearing',description:'Cross-examination of PW-1 partially completed'}], createdBy:userMap['Rajesh Kumar'] },
      { caseNumber:'CS(OS) 567/2025', diaryNumber:'D-12345/2025', title:'Infosys Ltd. vs. DataTech Solutions', client:clientMap['Infosys Limited'], clientName:'Infosys Limited', courtKey:'DHC', courtName:COURTS.DHC, bench:'Single Bench – Justice Vibhu Bakhru', opposingParty:'DataTech Solutions Pvt. Ltd.', advocate:userMap['Priya Nair'], advocateName:'Adv. Priya Nair', filingType:'Commercial Suit', status:'Active', priority:'High', stage:2, filingDate:'2025-06-10', registrationDate:'2025-06-15', nextHearingDate:'2026-04-08', lastOrderDate:'2026-03-22', filingDeadline:'2026-04-15', lastHearingOutcome:'Written statement filed. Replication to be filed within 30 days.', causeListRef:'Cause List No. 38, Item 14, Court No. 7', nextActionDate:'2026-04-07', description:'Intellectual property dispute concerning proprietary software algorithms and trade secrets.', billingType:'Hourly', totalBilled:1400000, totalPaid:1000000, adjournmentHistory:[{date:'2026-02-10',reason:'Plaintiff counsel not available',nextDate:'2026-03-22'}], timeline:[{date:'2025-06-10',type:'Filing',description:'Commercial suit filed for IP infringement'},{date:'2025-06-15',type:'Registration',description:'Suit registered at Delhi High Court'},{date:'2025-07-20',type:'Hearing',description:'Summons issued to defendant'},{date:'2025-09-15',type:'Order',description:'Case admitted. Written statement directed within 30 days.'},{date:'2026-02-10',type:'Adjournment',description:'Counsel not available'},{date:'2026-03-22',type:'Hearing',description:'Written statement filed and accepted'}], createdBy:userMap['Rajesh Kumar'] },
      { caseNumber:'WP 2345/2024', diaryNumber:'D-67890/2024', title:'TCS vs. Maharashtra State Tax Authority', client:clientMap['Tata Consultancy Services'], clientName:'Tata Consultancy Services', courtKey:'BHC', courtName:COURTS.BHC, bench:'Division Bench – Justice G.S. Patel, Justice Neela Gokhale', opposingParty:'State of Maharashtra (Tax Dept.)', advocate:userMap['Suresh Iyer'], advocateName:'Adv. Suresh Iyer', filingType:'Writ Petition', status:'Active', priority:'High', stage:5, filingDate:'2024-03-20', registrationDate:'2024-03-25', nextHearingDate:'2026-04-12', lastOrderDate:'2026-03-25', filingDeadline:'2026-04-20', lastHearingOutcome:'Arguments of petitioner concluded. Respondent to argue on next date.', causeListRef:'Cause List No. 44, Item 3, Court No. 1', nextActionDate:'2026-04-11', description:'Challenge to GST assessment order demanding ₹45 Crores. Involves interpretation of input tax credit provisions under CGST Act.', billingType:'Fixed Fee', totalBilled:2000000, totalPaid:2000000, adjournmentHistory:[{date:'2026-01-15',reason:'State counsel sought time for instructions',nextDate:'2026-02-20'},{date:'2026-02-20',reason:'Part-heard matter carried forward',nextDate:'2026-03-25'}], timeline:[{date:'2024-03-20',type:'Filing',description:'WP filed challenging GST demand of ₹45 Cr'},{date:'2024-03-25',type:'Registration',description:'Registered at Bombay High Court'},{date:'2024-05-10',type:'Hearing',description:'Admission hearing – interim stay granted'},{date:'2024-08-15',type:'Order',description:'Written statement directed'},{date:'2025-02-10',type:'Stage',description:'Evidence stage completed'},{date:'2025-10-15',type:'Stage',description:'Arguments commenced'},{date:'2026-03-25',type:'Hearing',description:'Petitioner arguments concluded'}], createdBy:userMap['Rajesh Kumar'] },
      { caseNumber:'ARB.P. 789/2025', diaryNumber:'D-23456/2025', title:'Adani Ports vs. Global Shipping Corp.', client:clientMap['Adani Group'], clientName:'Adani Group', courtKey:'BHC', courtName:COURTS.BHC, bench:'Single Bench – Justice B.P. Colabawalla', opposingParty:'Global Shipping Corporation Ltd.', advocate:userMap['Meera Desai'], advocateName:'Adv. Meera Desai', filingType:'Arbitration Petition', status:'Active', priority:'Critical', stage:3, filingDate:'2025-02-14', registrationDate:'2025-02-18', nextHearingDate:'2026-04-05', lastOrderDate:'2026-03-20', filingDeadline:'2026-04-08', lastHearingOutcome:'Written statements exchanged. List of documents directed within 2 weeks.', causeListRef:'Cause List No. 41, Item 6, Court No. 5', nextActionDate:'2026-04-04', description:'Commercial arbitration dispute relating to port handling charges and force majeure claims. Claim value: ₹120 Crores.', billingType:'Event-Based', totalBilled:3500000, totalPaid:2500000, adjournmentHistory:[], timeline:[{date:'2025-02-14',type:'Filing',description:'Arbitration petition filed under Section 11'},{date:'2025-02-18',type:'Registration',description:'Registered and numbered'},{date:'2025-04-10',type:'Hearing',description:'Arbitrator appointed by consent'},{date:'2025-08-20',type:'Order',description:'Statement of claim filed'},{date:'2026-01-15',type:'Stage',description:'Written statements exchanged'},{date:'2026-03-20',type:'Hearing',description:'List of documents directed'}], createdBy:userMap['Rajesh Kumar'] },
      { caseNumber:'CS 123/2024', diaryNumber:'D-34567/2024', title:'Arun Mehta vs. Heritage Properties', client:clientMap['Arun Mehta'], clientName:'Arun Mehta', courtKey:'DCMUM', courtName:COURTS.DCMUM, bench:'Civil Judge, Senior Division – Court No. 12', opposingParty:'Heritage Properties Pvt. Ltd.', advocate:userMap['Amit Sharma'], advocateName:'Adv. Amit Sharma', filingType:'Civil Suit', status:'Active', priority:'Medium', stage:1, filingDate:'2024-11-10', registrationDate:'2024-11-15', nextHearingDate:'2026-04-15', lastOrderDate:'2026-03-10', filingDeadline:'2026-04-25', lastHearingOutcome:'Summons served on defendant. Appearance directed on next date.', causeListRef:'Cause List, Court No. 12, Sr. No. 23', nextActionDate:'2026-04-14', description:'Suit for specific performance of agreement to sell property at Bandra, Mumbai.', billingType:'Fixed Fee', totalBilled:250000, totalPaid:150000, adjournmentHistory:[{date:'2026-02-05',reason:'Service of summons pending',nextDate:'2026-03-10'}], timeline:[{date:'2024-11-10',type:'Filing',description:'Suit for specific performance of sale agreement'},{date:'2024-11-15',type:'Registration',description:'Registered at District Court, Mumbai'},{date:'2025-01-20',type:'Hearing',description:'Summons issued'},{date:'2026-02-05',type:'Adjournment',description:'Summons not served'},{date:'2026-03-10',type:'Hearing',description:'Summons served. Next for admission.'}], createdBy:userMap['Rajesh Kumar'] },
      { caseNumber:'CRL.MC 456/2025', diaryNumber:'D-78901/2025', title:'Priya Sharma vs. State of Delhi', client:clientMap['Priya Sharma'], clientName:'Priya Sharma', courtKey:'DCDEL', courtName:COURTS.DCDEL, bench:'Metropolitan Magistrate – Court No. 8', opposingParty:'State of NCT Delhi', advocate:userMap['Kavita Reddy'], advocateName:'Adv. Kavita Reddy', filingType:'Criminal Miscellaneous', status:'Active', priority:'High', stage:3, filingDate:'2025-04-05', registrationDate:'2025-04-08', nextHearingDate:'2026-04-18', lastOrderDate:'2026-03-28', filingDeadline:'2026-04-22', lastHearingOutcome:'Evidence of prosecution being recorded. PW-2 examined.', causeListRef:'Cause List, Court No. 8, Sr. No. 15', nextActionDate:'2026-04-17', description:'Quashing petition under Section 482 CrPC. Cheque bounce under Section 138 NI Act. Amount: ₹15 Lakhs.', billingType:'Retainership', totalBilled:175000, totalPaid:120000, adjournmentHistory:[{date:'2026-03-05',reason:'Prosecution witness not available',nextDate:'2026-03-28'}], timeline:[{date:'2025-04-05',type:'Filing',description:'Criminal miscellaneous petition filed'},{date:'2025-04-08',type:'Registration',description:'Case registered'},{date:'2025-06-15',type:'Hearing',description:'Charges framed'},{date:'2025-09-20',type:'Stage',description:'Evidence stage commenced'},{date:'2026-03-05',type:'Adjournment',description:'PW not available'},{date:'2026-03-28',type:'Hearing',description:'PW-2 examined'}], createdBy:userMap['Rajesh Kumar'] },
      { caseNumber:'WP(C) 890/2025', diaryNumber:'D-56789/2025', title:'Reliance Jio vs. TRAI', client:clientMap['Reliance Industries Ltd.'], clientName:'Reliance Industries Ltd.', courtKey:'SC', courtName:COURTS.SC, bench:'Division Bench – Justice Surya Kant, Justice Dipankar Datta', opposingParty:'TRAI & Others', advocate:userMap['Rajesh Kumar'], advocateName:'Adv. Rajesh Kumar', filingType:'Writ Petition (Civil)', status:'Active', priority:'High', stage:2, filingDate:'2025-09-01', registrationDate:'2025-09-05', nextHearingDate:'2026-04-20', lastOrderDate:'2026-03-15', filingDeadline:'2026-04-28', lastHearingOutcome:'Case admitted. Counter affidavit directed within 4 weeks.', causeListRef:'Cause List No. 55, Item 12, Court No. 6', nextActionDate:'2026-04-19', description:'Challenge to TRAI regulatory framework on telecom tariff structure.', billingType:'Hourly', totalBilled:900000, totalPaid:600000, adjournmentHistory:[], timeline:[{date:'2025-09-01',type:'Filing',description:'Challenge to TRAI regulation on tariff framework'},{date:'2025-09-05',type:'Registration',description:'Registered at Supreme Court'},{date:'2025-11-10',type:'Hearing',description:'Admission hearing – case admitted'},{date:'2026-03-15',type:'Order',description:'Counter affidavit directed within 4 weeks'}], createdBy:userMap['Rajesh Kumar'] },
      { caseNumber:'TA 234/2025', diaryNumber:'D-89012/2025', title:'Infosys vs. Income Tax Department', client:clientMap['Infosys Limited'], clientName:'Infosys Limited', courtKey:'BHC', courtName:COURTS.BHC, bench:'Income Tax Appellate Tribunal – Bench B', opposingParty:'Deputy CIT, Circle 1(1)', advocate:userMap['Suresh Iyer'], advocateName:'Adv. Suresh Iyer', filingType:'Tax Appeal', status:'Active', priority:'Medium', stage:5, filingDate:'2025-01-20', registrationDate:'2025-01-25', nextHearingDate:'2026-04-22', lastOrderDate:'2026-03-30', filingDeadline:'2026-05-01', lastHearingOutcome:'Arguments of appellant partially heard.', causeListRef:'Cause List – ITAT Bench B, Sr. No. 5', nextActionDate:'2026-04-21', description:'Appeal against income tax assessment order for AY 2023-24. Demand: ₹230 Crores.', billingType:'Fixed Fee', totalBilled:1400000, totalPaid:1400000, adjournmentHistory:[{date:'2026-03-01',reason:'Tribunal adjourned for administrative reasons',nextDate:'2026-03-30'}], timeline:[{date:'2025-01-20',type:'Filing',description:'Tax appeal filed against assessment order'},{date:'2025-01-25',type:'Registration',description:'Appeal registered at ITAT'},{date:'2025-05-10',type:'Hearing',description:'Preliminary hearing'},{date:'2025-08-20',type:'Stage',description:'Evidence completed'},{date:'2026-03-01',type:'Adjournment',description:'Tribunal adjourned'},{date:'2026-03-30',type:'Hearing',description:'Arguments partially heard'}], createdBy:userMap['Rajesh Kumar'] },
      { caseNumber:'SLP(C) 5678/2025', diaryNumber:'D-90123/2025', title:'Adani Power vs. CERC', client:clientMap['Adani Group'], clientName:'Adani Group', courtKey:'SC', courtName:COURTS.SC, bench:'Division Bench – Justice B.R. Gavai, Justice Aravind Kumar', opposingParty:'Central Electricity Regulatory Commission', advocate:userMap['Meera Desai'], advocateName:'Adv. Meera Desai', filingType:'Special Leave Petition (Civil)', status:'Active', priority:'Critical', stage:1, filingDate:'2025-11-15', registrationDate:'2025-11-20', nextHearingDate:'2026-04-06', lastOrderDate:'2026-03-22', filingDeadline:'2026-04-12', lastHearingOutcome:'Notice issued. Tagged with connected matters.', causeListRef:'Cause List No. 50, Item 2, Court No. 2', nextActionDate:'2026-04-05', description:'Challenge to CERC tariff order. Financial impact: ₹800 Crores.', billingType:'Milestone-Based', totalBilled:1700000, totalPaid:1000000, adjournmentHistory:[], timeline:[{date:'2025-11-15',type:'Filing',description:'SLP filed against APTEL order on tariff determination'},{date:'2025-11-20',type:'Registration',description:'Registered at Supreme Court'},{date:'2026-01-10',type:'Hearing',description:'Notice issued to respondents'},{date:'2026-03-22',type:'Order',description:'Tagged with connected matters for hearing'}], createdBy:userMap['Rajesh Kumar'] },
      { caseNumber:'CS(COMM) 345/2024', diaryNumber:'D-45670/2024', title:'TCS vs. ByteWorks Technologies', client:clientMap['Tata Consultancy Services'], clientName:'Tata Consultancy Services', courtKey:'BHC', courtName:COURTS.BHC, bench:'Commercial Division – Justice R.I. Chagla', opposingParty:'ByteWorks Technologies Ltd.', advocate:userMap['Rajesh Kumar'], advocateName:'Adv. Rajesh Kumar', filingType:'Commercial Suit', status:'Active', priority:'Medium', stage:4, filingDate:'2024-06-01', registrationDate:'2024-06-05', nextHearingDate:'2026-04-25', lastOrderDate:'2026-03-28', filingDeadline:'2026-05-05', lastHearingOutcome:'Chief examination of PW-1 completed.', causeListRef:'Cause List – Commercial Division, Sr. No. 10', nextActionDate:'2026-04-24', description:'Breach of master service agreement. Damages claimed: ₹50 Crores.', billingType:'Hourly', totalBilled:1200000, totalPaid:800000, adjournmentHistory:[{date:'2025-11-20',reason:'Witness not available',nextDate:'2026-01-15'},{date:'2026-01-15',reason:'Court functioning disrupted due to strike',nextDate:'2026-02-20'}], timeline:[{date:'2024-06-01',type:'Filing',description:'Commercial suit for breach of service agreement'},{date:'2024-06-05',type:'Registration',description:'Suit registered at Bombay HC Commercial Division'},{date:'2024-09-10',type:'Hearing',description:'Written statement filed by defendant'},{date:'2025-03-15',type:'Stage',description:'Evidence stage commenced'},{date:'2025-11-20',type:'Adjournment',description:'Witness not available'},{date:'2026-03-28',type:'Hearing',description:'PW-1 chief examination completed'}], createdBy:userMap['Rajesh Kumar'] },
      { caseNumber:'WP 678/2025', diaryNumber:'D-67891/2025', title:'Wipro vs. Karnataka IT Dept.', client:clientMap['Wipro Limited'], clientName:'Wipro Limited', courtKey:'BHC', courtName:'Karnataka High Court', bench:'Single Bench – Justice M. Nagaprasanna', opposingParty:'State of Karnataka (IT Department)', advocate:userMap['Kavita Reddy'], advocateName:'Adv. Kavita Reddy', filingType:'Writ Petition', status:'Active', priority:'Medium', stage:3, filingDate:'2025-05-20', registrationDate:'2025-05-25', nextHearingDate:'2026-04-28', lastOrderDate:'2026-03-18', filingDeadline:'2026-05-10', lastHearingOutcome:'Counter filed by state. Rejoinder directed within 3 weeks.', causeListRef:'Cause List No. 32, Item 18, Court No. 4', nextActionDate:'2026-04-27', description:'Challenge to withdrawal of IT sector incentives by Karnataka government.', billingType:'Retainership', totalBilled:1800000, totalPaid:1500000, adjournmentHistory:[], timeline:[{date:'2025-05-20',type:'Filing',description:'WP challenging IT incentive withdrawal'},{date:'2025-05-25',type:'Registration',description:'Registered at Karnataka HC'},{date:'2025-08-10',type:'Hearing',description:'Interim order – status quo maintained'},{date:'2026-03-18',type:'Hearing',description:'Counter filed. Rejoinder directed.'}], createdBy:userMap['Rajesh Kumar'] },
      { caseNumber:'RCS 901/2024', diaryNumber:'D-90124/2024', title:'Bajaj Auto vs. SpeedParts India', client:clientMap['Bajaj Auto Ltd.'], clientName:'Bajaj Auto Ltd.', courtKey:'DCMUM', courtName:COURTS.DCMUM, bench:'Civil Judge – Court No. 6', opposingParty:'SpeedParts India Pvt. Ltd.', advocate:userMap['Amit Sharma'], advocateName:'Adv. Amit Sharma', filingType:'Regular Civil Suit', status:'Active', priority:'Low', stage:6, filingDate:'2024-02-10', registrationDate:'2024-02-15', nextHearingDate:'2026-05-02', lastOrderDate:'2026-03-25', filingDeadline:'2026-05-15', lastHearingOutcome:'Final arguments of plaintiff concluded.', causeListRef:'Cause List, Court No. 6, Sr. No. 8', nextActionDate:'2026-05-01', description:'Trademark infringement suit. Seeking permanent injunction and damages of ₹5 Crores.', billingType:'Fixed Fee', totalBilled:920000, totalPaid:920000, adjournmentHistory:[{date:'2026-02-15',reason:'Part heard – insufficient time',nextDate:'2026-03-25'}], timeline:[{date:'2024-02-10',type:'Filing',description:'Suit for trademark infringement and passing off'},{date:'2024-02-15',type:'Registration',description:'Case registered'},{date:'2024-05-20',type:'Hearing',description:'Written statement filed'},{date:'2024-10-10',type:'Stage',description:'Evidence completed'},{date:'2025-06-15',type:'Stage',description:'Arguments commenced'},{date:'2025-12-20',type:'Stage',description:'Final hearing stage'},{date:'2026-03-25',type:'Hearing',description:'Plaintiff arguments concluded'}], createdBy:userMap['Rajesh Kumar'] },
      { caseNumber:'EP 456/2024', diaryNumber:'D-45671/2024', title:'Reliance Retail vs. QuickMart', client:clientMap['Reliance Industries Ltd.'], clientName:'Reliance Industries Ltd.', courtKey:'DHC', courtName:COURTS.DHC, bench:'Single Bench – Justice C. Hari Shankar', opposingParty:'QuickMart Retail Pvt. Ltd.', advocate:userMap['Priya Nair'], advocateName:'Adv. Priya Nair', filingType:'Execution Petition', status:'Pending', priority:'Medium', stage:7, filingDate:'2024-07-15', registrationDate:'2024-07-20', nextHearingDate:'2026-04-30', lastOrderDate:'2026-03-12', filingDeadline:'2026-05-10', lastHearingOutcome:'Order reserved. Judgment awaited.', causeListRef:'Cause List No. 35, Item 20, Court No. 9', nextActionDate:'2026-04-29', description:'Execution of commercial court decree. ₹18 Crores damages.', billingType:'Event-Based', totalBilled:800000, totalPaid:500000, adjournmentHistory:[], timeline:[{date:'2024-07-15',type:'Filing',description:'Execution petition filed for decree enforcement'},{date:'2024-07-20',type:'Registration',description:'EP registered at Delhi HC'},{date:'2024-12-10',type:'Hearing',description:'Objections to execution heard'},{date:'2025-06-20',type:'Stage',description:'Arguments completed'},{date:'2026-03-12',type:'Order',description:'Order reserved after final hearing'}], createdBy:userMap['Rajesh Kumar'] }
    ];
    const casesCreated = await Case.create(casesData);
    console.log(`Created ${casesCreated.length} cases.`);

    const caseMap = {};
    casesCreated.forEach(c => { caseMap[c.caseNumber] = c._id; });

    // === DOCUMENTS ===
    const docsData = [
      { title:'Vakalatnama – Supreme Court', type:'Vakalatnama', category:'Legal Authority', caseId:caseMap['WP(C) 1234/2025'], uploadedBy:userMap['Rajesh Kumar'], uploadedByName:'Adv. Rajesh Kumar', fileSize:'245 KB', status:'Verified', uploadDate:'2024-08-14' },
      { title:'Writ Petition with Annexures', type:'Petition', category:'Court Filing', caseId:caseMap['WP(C) 1234/2025'], uploadedBy:userMap['Rajesh Kumar'], uploadedByName:'Adv. Rajesh Kumar', fileSize:'2.1 MB', status:'Filed', uploadDate:'2024-08-15' },
      { title:'Affidavit in Support', type:'Affidavit', category:'Court Filing', caseId:caseMap['WP(C) 1234/2025'], uploadedBy:userMap['Rajesh Kumar'], uploadedByName:'Adv. Rajesh Kumar', fileSize:'1.8 MB', status:'Filed', uploadDate:'2024-08-15' },
      { title:'Power of Attorney', type:'Power of Attorney', category:'Legal Authority', caseId:caseMap['CS(OS) 567/2025'], uploadedBy:userMap['Priya Nair'], uploadedByName:'Adv. Priya Nair', fileSize:'180 KB', status:'Verified', uploadDate:'2025-06-09' },
      { title:'IP Assignment Agreement', type:'Evidence Document', category:'Evidence', caseId:caseMap['CS(OS) 567/2025'], uploadedBy:userMap['Priya Nair'], uploadedByName:'Legal Team', fileSize:'3.5 MB', status:'Uploaded', uploadDate:'2025-07-15' },
      { title:'GST Assessment Order', type:'GST Filing Attachment', category:'Tax Document', caseId:caseMap['WP 2345/2024'], uploadedBy:userMap['Suresh Iyer'], uploadedByName:'Adv. Suresh Iyer', fileSize:'5.2 MB', status:'Verified', uploadDate:'2024-03-19' },
      { title:'Vakalatnama – Bombay HC', type:'Vakalatnama', category:'Legal Authority', caseId:caseMap['WP 2345/2024'], uploadedBy:userMap['Suresh Iyer'], uploadedByName:'Adv. Suresh Iyer', fileSize:'210 KB', status:'Filed', uploadDate:'2024-03-19' },
      { title:'Arbitration Agreement', type:'Evidence Document', category:'Contract', caseId:caseMap['ARB.P. 789/2025'], uploadedBy:userMap['Meera Desai'], uploadedByName:'Adv. Meera Desai', fileSize:'890 KB', status:'Verified', uploadDate:'2025-02-13' },
      { title:'Sale Agreement', type:'Sale Deed', category:'Property Document', caseId:caseMap['CS 123/2024'], uploadedBy:userMap['Amit Sharma'], uploadedByName:'Adv. Amit Sharma', fileSize:'1.2 MB', status:'Verified', uploadDate:'2024-11-09' },
      { title:'Aadhaar Card – Arun Mehta', type:'Aadhaar Copy', category:'Identity Document', caseId:caseMap['CS 123/2024'], uploadedBy:userMap['Amit Sharma'], uploadedByName:'Client', fileSize:'320 KB', status:'Verified', uploadDate:'2024-11-09' },
      { title:'PAN Card – Arun Mehta', type:'PAN Copy', category:'Identity Document', caseId:caseMap['CS 123/2024'], uploadedBy:userMap['Amit Sharma'], uploadedByName:'Client', fileSize:'150 KB', status:'Verified', uploadDate:'2024-11-09' },
      { title:'Rent Agreement', type:'Rent Agreement', category:'Property Document', caseId:caseMap['CRL.MC 456/2025'], uploadedBy:userMap['Kavita Reddy'], uploadedByName:'Adv. Kavita Reddy', fileSize:'680 KB', status:'Uploaded', uploadDate:'2025-04-04' },
      { title:'Bounced Cheque Copy', type:'Evidence Document', category:'Evidence', caseId:caseMap['CRL.MC 456/2025'], uploadedBy:userMap['Kavita Reddy'], uploadedByName:'Client', fileSize:'420 KB', status:'Verified', uploadDate:'2025-04-04' },
      { title:'Port Handling Agreement', type:'Evidence Document', category:'Contract', caseId:caseMap['ARB.P. 789/2025'], uploadedBy:userMap['Meera Desai'], uploadedByName:'Adv. Meera Desai', fileSize:'4.5 MB', status:'Filed', uploadDate:'2025-02-14' },
      { title:'SLP Memo of Parties', type:'Petition', category:'Court Filing', caseId:caseMap['SLP(C) 5678/2025'], uploadedBy:userMap['Meera Desai'], uploadedByName:'Adv. Meera Desai', fileSize:'560 KB', status:'Filed', uploadDate:'2025-11-15' },
      { title:'Master Service Agreement', type:'Evidence Document', category:'Contract', caseId:caseMap['CS(COMM) 345/2024'], uploadedBy:userMap['Rajesh Kumar'], uploadedByName:'Legal Team', fileSize:'2.8 MB', status:'Verified', uploadDate:'2024-06-01' },
      { title:'Counter Affidavit – TRAI', type:'Counter Affidavit', category:'Court Filing', caseId:caseMap['WP(C) 890/2025'], uploadedBy:userMap['Rajesh Kumar'], uploadedByName:'Respondent', fileSize:'1.9 MB', status:'Pending Review', uploadDate:'2026-03-15' },
      { title:'Tax Assessment Order AY23-24', type:'GST Filing Attachment', category:'Tax Document', caseId:caseMap['TA 234/2025'], uploadedBy:userMap['Suresh Iyer'], uploadedByName:'Adv. Suresh Iyer', fileSize:'3.8 MB', status:'Verified', uploadDate:'2025-01-19' },
      { title:'SEZ Notification', type:'Evidence Document', category:'Government Document', caseId:caseMap['WP 678/2025'], uploadedBy:userMap['Kavita Reddy'], uploadedByName:'Legal Team', fileSize:'1.1 MB', status:'Uploaded', uploadDate:'2025-05-19' },
      { title:'Trademark Registration Certificate', type:'Evidence Document', category:'IP Document', caseId:caseMap['RCS 901/2024'], uploadedBy:userMap['Amit Sharma'], uploadedByName:'Adv. Amit Sharma', fileSize:'450 KB', status:'Verified', uploadDate:'2024-02-09' },
      { title:'Written Statement by UoI', type:'Written Statement', category:'Court Filing', caseId:caseMap['WP(C) 1234/2025'], uploadedBy:userMap['Rajesh Kumar'], uploadedByName:'Respondent', fileSize:'2.4 MB', status:'Filed', uploadDate:'2025-01-15' },
      { title:'Compliance Report Q3-2025', type:'Compliance Report', category:'Regulatory', caseId:caseMap['WP 2345/2024'], uploadedBy:userMap['Suresh Iyer'], uploadedByName:'Legal Team', fileSize:'1.5 MB', status:'Uploaded', uploadDate:'2025-10-01' },
      { title:'Decree Copy', type:'Court Order', category:'Court Filing', caseId:caseMap['EP 456/2024'], uploadedBy:userMap['Priya Nair'], uploadedByName:'Adv. Priya Nair', fileSize:'780 KB', status:'Verified', uploadDate:'2024-07-14' }
    ];
    const docs = await Document.create(docsData);
    console.log(`Created ${docs.length} documents.`);

    // === INVOICES ===
    const invoicesData = [
      { invoiceNumber:'LF/2025-26/001', clientId:clientMap['Reliance Industries Ltd.'], clientName:'Reliance Industries Ltd.', caseId:caseMap['WP(C) 1234/2025'], amount:600000, gst:108000, total:708000, type:'Milestone-Based', status:'Paid', description:'Milestone 3 – Evidence stage completion', date:'2026-03-01', dueDate:'2026-03-31', paidDate:'2026-03-15', createdBy:userMap['Rajesh Kumar'] },
      { invoiceNumber:'LF/2025-26/002', clientId:clientMap['Reliance Industries Ltd.'], clientName:'Reliance Industries Ltd.', caseId:caseMap['WP(C) 1234/2025'], amount:600000, gst:108000, total:708000, type:'Milestone-Based', status:'Pending', description:'Milestone 4 – Arguments preparation', date:'2026-03-15', dueDate:'2026-04-14', paidDate:null, createdBy:userMap['Rajesh Kumar'] },
      { invoiceNumber:'LF/2025-26/003', clientId:clientMap['Infosys Limited'], clientName:'Infosys Limited', caseId:caseMap['CS(OS) 567/2025'], amount:400000, gst:72000, total:472000, type:'Hourly', status:'Overdue', description:'80 hours @ ₹5,000/hr – Feb 2026', date:'2026-02-01', dueDate:'2026-03-03', paidDate:null, createdBy:userMap['Rajesh Kumar'] },
      { invoiceNumber:'LF/2025-26/004', clientId:clientMap['Tata Consultancy Services'], clientName:'Tata Consultancy Services', caseId:caseMap['WP 2345/2024'], amount:500000, gst:90000, total:590000, type:'Fixed Fee', status:'Paid', description:'Phase 2 – Arguments stage', date:'2026-01-15', dueDate:'2026-02-14', paidDate:'2026-02-10', createdBy:userMap['Rajesh Kumar'] },
      { invoiceNumber:'LF/2025-26/005', clientId:clientMap['Adani Group'], clientName:'Adani Group', caseId:caseMap['ARB.P. 789/2025'], amount:1000000, gst:180000, total:1180000, type:'Event-Based', status:'Pending', description:'Arbitrator appointment & Statement of claim filing', date:'2026-03-20', dueDate:'2026-04-19', paidDate:null, createdBy:userMap['Rajesh Kumar'] },
      { invoiceNumber:'LF/2025-26/006', clientId:clientMap['Arun Mehta'], clientName:'Arun Mehta', caseId:caseMap['CS 123/2024'], amount:100000, gst:18000, total:118000, type:'Fixed Fee', status:'Overdue', description:'Retainer – Nov & Dec 2025', date:'2025-12-01', dueDate:'2025-12-31', paidDate:null, createdBy:userMap['Rajesh Kumar'] },
      { invoiceNumber:'LF/2025-26/007', clientId:clientMap['Priya Sharma'], clientName:'Priya Sharma', caseId:caseMap['CRL.MC 456/2025'], amount:55000, gst:9900, total:64900, type:'Retainership', status:'Pending', description:'Monthly retainer – March 2026', date:'2026-03-01', dueDate:'2026-03-31', paidDate:null, createdBy:userMap['Rajesh Kumar'] },
      { invoiceNumber:'LF/2025-26/008', clientId:clientMap['Adani Group'], clientName:'Adani Group', caseId:caseMap['SLP(C) 5678/2025'], amount:700000, gst:126000, total:826000, type:'Milestone-Based', status:'Overdue', description:'Milestone 1 – SLP filing and admission', date:'2026-02-15', dueDate:'2026-03-17', paidDate:null, createdBy:userMap['Rajesh Kumar'] },
      { invoiceNumber:'LF/2025-26/009', clientId:clientMap['Tata Consultancy Services'], clientName:'Tata Consultancy Services', caseId:caseMap['CS(COMM) 345/2024'], amount:400000, gst:72000, total:472000, type:'Hourly', status:'Pending', description:'80 hours @ ₹5,000/hr – March 2026', date:'2026-03-25', dueDate:'2026-04-24', paidDate:null, createdBy:userMap['Rajesh Kumar'] },
      { invoiceNumber:'LF/2025-26/010', clientId:clientMap['Wipro Limited'], clientName:'Wipro Limited', caseId:caseMap['WP 678/2025'], amount:300000, gst:54000, total:354000, type:'Retainership', status:'Paid', description:'Quarterly retainer Q1-2026', date:'2026-03-01', dueDate:'2026-03-31', paidDate:'2026-03-28', createdBy:userMap['Rajesh Kumar'] },
      { invoiceNumber:'LF/2025-26/011', clientId:clientMap['Bajaj Auto Ltd.'], clientName:'Bajaj Auto Ltd.', caseId:caseMap['RCS 901/2024'], amount:200000, gst:36000, total:236000, type:'Fixed Fee', status:'Paid', description:'Final arguments stage billing', date:'2026-01-10', dueDate:'2026-02-09', paidDate:'2026-02-05', createdBy:userMap['Rajesh Kumar'] },
      { invoiceNumber:'LF/2025-26/012', clientId:clientMap['Reliance Industries Ltd.'], clientName:'Reliance Industries Ltd.', caseId:caseMap['WP(C) 890/2025'], amount:300000, gst:54000, total:354000, type:'Hourly', status:'Pending', description:'60 hours @ ₹5,000/hr – TRAI matter', date:'2026-03-10', dueDate:'2026-04-09', paidDate:null, createdBy:userMap['Rajesh Kumar'] }
    ];
    const invs = await Invoice.create(invoicesData);
    console.log(`Created ${invs.length} invoices.`);

    // === TASKS ===
    const tasksData = [
      { caseId:caseMap['WP(C) 1234/2025'], title:'Prepare cross-examination brief for PW-2', assignee:'Adv. Rajesh Kumar', assigneeId:userMap['Rajesh Kumar'], dueDate:'2026-04-03', status:'In Progress', priority:'Critical', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['CS(OS) 567/2025'], title:'Draft replication to written statement', assignee:'Adv. Priya Nair', assigneeId:userMap['Priya Nair'], dueDate:'2026-04-15', status:'Pending', priority:'High', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['ARB.P. 789/2025'], title:'Compile list of documents for arbitration', assignee:'Adv. Meera Desai', assigneeId:userMap['Meera Desai'], dueDate:'2026-04-04', status:'In Progress', priority:'Critical', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['WP 2345/2024'], title:'Prepare rejoinder arguments', assignee:'Adv. Suresh Iyer', assigneeId:userMap['Suresh Iyer'], dueDate:'2026-04-11', status:'Pending', priority:'High', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['CS 123/2024'], title:'Follow up on summons service status', assignee:'Adv. Amit Sharma', assigneeId:userMap['Amit Sharma'], dueDate:'2026-04-14', status:'Pending', priority:'Medium', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['CRL.MC 456/2025'], title:'Prepare defense arguments for NI Act', assignee:'Adv. Kavita Reddy', assigneeId:userMap['Kavita Reddy'], dueDate:'2026-04-17', status:'Not Started', priority:'High', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['SLP(C) 5678/2025'], title:'File counter to CERC response', assignee:'Adv. Meera Desai', assigneeId:userMap['Meera Desai'], dueDate:'2026-04-05', status:'In Progress', priority:'Critical', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['CS(COMM) 345/2024'], title:'Prepare witness for cross-examination', assignee:'Adv. Rajesh Kumar', assigneeId:userMap['Rajesh Kumar'], dueDate:'2026-04-24', status:'Not Started', priority:'Medium', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['WP(C) 890/2025'], title:'Review TRAI counter affidavit', assignee:'Adv. Rajesh Kumar', assigneeId:userMap['Rajesh Kumar'], dueDate:'2026-04-19', status:'Pending', priority:'High', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['WP 2345/2024'], title:'Submit GST compliance report', assignee:'Legal Team', dueDate:'2026-03-28', status:'Overdue', priority:'Critical', createdBy:userMap['Rajesh Kumar'] }
    ];
    const tks = await Task.create(tasksData);
    console.log(`Created ${tks.length} tasks.`);

    // === CALENDAR EVENTS ===
    const eventsData = [
      { caseId:caseMap['WP(C) 1234/2025'], title:'Hearing – Reliance vs. UoI', date:'2026-04-04', time:'10:30 AM', court:COURTS.SC, type:'Hearing', priority:'Critical', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['ARB.P. 789/2025'], title:'Hearing – Adani Ports Arbitration', date:'2026-04-05', time:'11:00 AM', court:COURTS.BHC, type:'Hearing', priority:'Critical', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['SLP(C) 5678/2025'], title:'Hearing – Adani Power vs. CERC', date:'2026-04-06', time:'10:00 AM', court:COURTS.SC, type:'Hearing', priority:'Critical', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['CS(OS) 567/2025'], title:'Hearing – Infosys vs. DataTech', date:'2026-04-08', time:'02:00 PM', court:COURTS.DHC, type:'Hearing', priority:'High', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['WP 2345/2024'], title:'Hearing – TCS vs. Maha Tax', date:'2026-04-12', time:'10:30 AM', court:COURTS.BHC, type:'Hearing', priority:'High', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['CS 123/2024'], title:'Hearing – Mehta Property Suit', date:'2026-04-15', time:'11:30 AM', court:COURTS.DCMUM, type:'Hearing', priority:'Medium', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['CRL.MC 456/2025'], title:'Hearing – Priya NI Act Matter', date:'2026-04-18', time:'02:30 PM', court:COURTS.DCDEL, type:'Hearing', priority:'High', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['WP(C) 890/2025'], title:'Hearing – Jio vs. TRAI', date:'2026-04-20', time:'10:00 AM', court:COURTS.SC, type:'Hearing', priority:'High', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['TA 234/2025'], title:'Hearing – Infosys Tax Appeal', date:'2026-04-22', time:'11:00 AM', court:COURTS.BHC, type:'Hearing', priority:'Medium', createdBy:userMap['Rajesh Kumar'] },
      { caseId:null, title:'GST Filing Deadline – Q4 FY26', date:'2026-04-30', time:'All Day', court:'', type:'Deadline', priority:'High', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['CS(COMM) 345/2024'], title:'Hearing – TCS vs. ByteWorks', date:'2026-04-25', time:'10:30 AM', court:COURTS.BHC, type:'Hearing', priority:'Medium', createdBy:userMap['Rajesh Kumar'] },
      { caseId:null, title:'Bar Council Meeting', date:'2026-04-10', time:'04:00 PM', court:'', type:'Meeting', priority:'Low', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['WP(C) 1234/2025'], title:'Filing Deadline – Evidence Documents', date:'2026-04-10', time:'EOD', court:COURTS.SC, type:'Deadline', priority:'Critical', createdBy:userMap['Rajesh Kumar'] },
      { caseId:caseMap['ARB.P. 789/2025'], title:'Filing Deadline – Document List', date:'2026-04-08', time:'EOD', court:COURTS.BHC, type:'Deadline', priority:'Critical', createdBy:userMap['Rajesh Kumar'] }
    ];
    const evts = await CalendarEvent.create(eventsData);
    console.log(`Created ${evts.length} calendar events.`);

    console.log('\n=== SEED COMPLETE ===');
    console.log('\nDemo Credentials:');
    console.log('  Admin:  admin@legalflow.in / admin123');
    console.log('  Lawyer: priya@legalflow.in / lawyer123');
    console.log('  Lawyer: suresh@legalflow.in / lawyer123');
    console.log('  Lawyer: meera@legalflow.in / lawyer123');
    console.log('  Lawyer: amit@legalflow.in / lawyer123');
    console.log('  Lawyer: kavita@legalflow.in / lawyer123');

    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
